// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	matchfacade "github.com/itimky/spindle/pkg/facade/match"

	mock "github.com/stretchr/testify/mock"
)

// MockmatchFacade is an autogenerated mock type for the matchFacade type
type MockmatchFacade struct {
	mock.Mock
}

type MockmatchFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *MockmatchFacade) EXPECT() *MockmatchFacade_Expecter {
	return &MockmatchFacade_Expecter{mock: &_m.Mock}
}

// ProcessAnswer provides a mock function with given fields: ctx, params
func (_m *MockmatchFacade) ProcessAnswer(ctx context.Context, params matchfacade.ProcessAnswerParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ProcessAnswer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, matchfacade.ProcessAnswerParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockmatchFacade_ProcessAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessAnswer'
type MockmatchFacade_ProcessAnswer_Call struct {
	*mock.Call
}

// ProcessAnswer is a helper method to define mock.On call
//   - ctx context.Context
//   - params matchfacade.ProcessAnswerParams
func (_e *MockmatchFacade_Expecter) ProcessAnswer(ctx interface{}, params interface{}) *MockmatchFacade_ProcessAnswer_Call {
	return &MockmatchFacade_ProcessAnswer_Call{Call: _e.mock.On("ProcessAnswer", ctx, params)}
}

func (_c *MockmatchFacade_ProcessAnswer_Call) Run(run func(ctx context.Context, params matchfacade.ProcessAnswerParams)) *MockmatchFacade_ProcessAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(matchfacade.ProcessAnswerParams))
	})
	return _c
}

func (_c *MockmatchFacade_ProcessAnswer_Call) Return(_a0 error) *MockmatchFacade_ProcessAnswer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockmatchFacade_ProcessAnswer_Call) RunAndReturn(run func(context.Context, matchfacade.ProcessAnswerParams) error) *MockmatchFacade_ProcessAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockmatchFacade creates a new instance of MockmatchFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockmatchFacade(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockmatchFacade {
	mock := &MockmatchFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
