// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	systemfacade "github.com/itimky/spindle/pkg/facade/system"
)

// MocksystemFacade is an autogenerated mock type for the systemFacade type
type MocksystemFacade struct {
	mock.Mock
}

type MocksystemFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *MocksystemFacade) EXPECT() *MocksystemFacade_Expecter {
	return &MocksystemFacade_Expecter{mock: &_m.Mock}
}

// BootstrapWeightMatrixStorage provides a mock function with given fields: ctx, params
func (_m *MocksystemFacade) BootstrapWeightMatrixStorage(ctx context.Context, params systemfacade.BootstrapWeightMatrixStorageParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for BootstrapWeightMatrixStorage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, systemfacade.BootstrapWeightMatrixStorageParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MocksystemFacade_BootstrapWeightMatrixStorage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BootstrapWeightMatrixStorage'
type MocksystemFacade_BootstrapWeightMatrixStorage_Call struct {
	*mock.Call
}

// BootstrapWeightMatrixStorage is a helper method to define mock.On call
//   - ctx context.Context
//   - params systemfacade.BootstrapWeightMatrixStorageParams
func (_e *MocksystemFacade_Expecter) BootstrapWeightMatrixStorage(ctx interface{}, params interface{}) *MocksystemFacade_BootstrapWeightMatrixStorage_Call {
	return &MocksystemFacade_BootstrapWeightMatrixStorage_Call{Call: _e.mock.On("BootstrapWeightMatrixStorage", ctx, params)}
}

func (_c *MocksystemFacade_BootstrapWeightMatrixStorage_Call) Run(run func(ctx context.Context, params systemfacade.BootstrapWeightMatrixStorageParams)) *MocksystemFacade_BootstrapWeightMatrixStorage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(systemfacade.BootstrapWeightMatrixStorageParams))
	})
	return _c
}

func (_c *MocksystemFacade_BootstrapWeightMatrixStorage_Call) Return(_a0 error) *MocksystemFacade_BootstrapWeightMatrixStorage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MocksystemFacade_BootstrapWeightMatrixStorage_Call) RunAndReturn(run func(context.Context, systemfacade.BootstrapWeightMatrixStorageParams) error) *MocksystemFacade_BootstrapWeightMatrixStorage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWeightMatrixStorage provides a mock function with given fields: ctx, params
func (_m *MocksystemFacade) UpdateWeightMatrixStorage(ctx context.Context, params systemfacade.UpdateWeightMatrixStorageParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWeightMatrixStorage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, systemfacade.UpdateWeightMatrixStorageParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MocksystemFacade_UpdateWeightMatrixStorage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWeightMatrixStorage'
type MocksystemFacade_UpdateWeightMatrixStorage_Call struct {
	*mock.Call
}

// UpdateWeightMatrixStorage is a helper method to define mock.On call
//   - ctx context.Context
//   - params systemfacade.UpdateWeightMatrixStorageParams
func (_e *MocksystemFacade_Expecter) UpdateWeightMatrixStorage(ctx interface{}, params interface{}) *MocksystemFacade_UpdateWeightMatrixStorage_Call {
	return &MocksystemFacade_UpdateWeightMatrixStorage_Call{Call: _e.mock.On("UpdateWeightMatrixStorage", ctx, params)}
}

func (_c *MocksystemFacade_UpdateWeightMatrixStorage_Call) Run(run func(ctx context.Context, params systemfacade.UpdateWeightMatrixStorageParams)) *MocksystemFacade_UpdateWeightMatrixStorage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(systemfacade.UpdateWeightMatrixStorageParams))
	})
	return _c
}

func (_c *MocksystemFacade_UpdateWeightMatrixStorage_Call) Return(_a0 error) *MocksystemFacade_UpdateWeightMatrixStorage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MocksystemFacade_UpdateWeightMatrixStorage_Call) RunAndReturn(run func(context.Context, systemfacade.UpdateWeightMatrixStorageParams) error) *MocksystemFacade_UpdateWeightMatrixStorage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocksystemFacade creates a new instance of MocksystemFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocksystemFacade(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocksystemFacade {
	mock := &MocksystemFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
