// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	sarama "github.com/IBM/sarama"
	mock "github.com/stretchr/testify/mock"
)

// MockConsumerGroupClaim is an autogenerated mock type for the ConsumerGroupClaim type
type MockConsumerGroupClaim struct {
	mock.Mock
}

type MockConsumerGroupClaim_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumerGroupClaim) EXPECT() *MockConsumerGroupClaim_Expecter {
	return &MockConsumerGroupClaim_Expecter{mock: &_m.Mock}
}

// HighWaterMarkOffset provides a mock function with given fields:
func (_m *MockConsumerGroupClaim) HighWaterMarkOffset() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HighWaterMarkOffset")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockConsumerGroupClaim_HighWaterMarkOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HighWaterMarkOffset'
type MockConsumerGroupClaim_HighWaterMarkOffset_Call struct {
	*mock.Call
}

// HighWaterMarkOffset is a helper method to define mock.On call
func (_e *MockConsumerGroupClaim_Expecter) HighWaterMarkOffset() *MockConsumerGroupClaim_HighWaterMarkOffset_Call {
	return &MockConsumerGroupClaim_HighWaterMarkOffset_Call{Call: _e.mock.On("HighWaterMarkOffset")}
}

func (_c *MockConsumerGroupClaim_HighWaterMarkOffset_Call) Run(run func()) *MockConsumerGroupClaim_HighWaterMarkOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumerGroupClaim_HighWaterMarkOffset_Call) Return(_a0 int64) *MockConsumerGroupClaim_HighWaterMarkOffset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumerGroupClaim_HighWaterMarkOffset_Call) RunAndReturn(run func() int64) *MockConsumerGroupClaim_HighWaterMarkOffset_Call {
	_c.Call.Return(run)
	return _c
}

// InitialOffset provides a mock function with given fields:
func (_m *MockConsumerGroupClaim) InitialOffset() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitialOffset")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockConsumerGroupClaim_InitialOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitialOffset'
type MockConsumerGroupClaim_InitialOffset_Call struct {
	*mock.Call
}

// InitialOffset is a helper method to define mock.On call
func (_e *MockConsumerGroupClaim_Expecter) InitialOffset() *MockConsumerGroupClaim_InitialOffset_Call {
	return &MockConsumerGroupClaim_InitialOffset_Call{Call: _e.mock.On("InitialOffset")}
}

func (_c *MockConsumerGroupClaim_InitialOffset_Call) Run(run func()) *MockConsumerGroupClaim_InitialOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumerGroupClaim_InitialOffset_Call) Return(_a0 int64) *MockConsumerGroupClaim_InitialOffset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumerGroupClaim_InitialOffset_Call) RunAndReturn(run func() int64) *MockConsumerGroupClaim_InitialOffset_Call {
	_c.Call.Return(run)
	return _c
}

// Messages provides a mock function with given fields:
func (_m *MockConsumerGroupClaim) Messages() <-chan *sarama.ConsumerMessage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Messages")
	}

	var r0 <-chan *sarama.ConsumerMessage
	if rf, ok := ret.Get(0).(func() <-chan *sarama.ConsumerMessage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *sarama.ConsumerMessage)
		}
	}

	return r0
}

// MockConsumerGroupClaim_Messages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Messages'
type MockConsumerGroupClaim_Messages_Call struct {
	*mock.Call
}

// Messages is a helper method to define mock.On call
func (_e *MockConsumerGroupClaim_Expecter) Messages() *MockConsumerGroupClaim_Messages_Call {
	return &MockConsumerGroupClaim_Messages_Call{Call: _e.mock.On("Messages")}
}

func (_c *MockConsumerGroupClaim_Messages_Call) Run(run func()) *MockConsumerGroupClaim_Messages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumerGroupClaim_Messages_Call) Return(_a0 <-chan *sarama.ConsumerMessage) *MockConsumerGroupClaim_Messages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumerGroupClaim_Messages_Call) RunAndReturn(run func() <-chan *sarama.ConsumerMessage) *MockConsumerGroupClaim_Messages_Call {
	_c.Call.Return(run)
	return _c
}

// Partition provides a mock function with given fields:
func (_m *MockConsumerGroupClaim) Partition() int32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Partition")
	}

	var r0 int32
	if rf, ok := ret.Get(0).(func() int32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int32)
	}

	return r0
}

// MockConsumerGroupClaim_Partition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Partition'
type MockConsumerGroupClaim_Partition_Call struct {
	*mock.Call
}

// Partition is a helper method to define mock.On call
func (_e *MockConsumerGroupClaim_Expecter) Partition() *MockConsumerGroupClaim_Partition_Call {
	return &MockConsumerGroupClaim_Partition_Call{Call: _e.mock.On("Partition")}
}

func (_c *MockConsumerGroupClaim_Partition_Call) Run(run func()) *MockConsumerGroupClaim_Partition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumerGroupClaim_Partition_Call) Return(_a0 int32) *MockConsumerGroupClaim_Partition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumerGroupClaim_Partition_Call) RunAndReturn(run func() int32) *MockConsumerGroupClaim_Partition_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function with given fields:
func (_m *MockConsumerGroupClaim) Topic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConsumerGroupClaim_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type MockConsumerGroupClaim_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *MockConsumerGroupClaim_Expecter) Topic() *MockConsumerGroupClaim_Topic_Call {
	return &MockConsumerGroupClaim_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *MockConsumerGroupClaim_Topic_Call) Run(run func()) *MockConsumerGroupClaim_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumerGroupClaim_Topic_Call) Return(_a0 string) *MockConsumerGroupClaim_Topic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumerGroupClaim_Topic_Call) RunAndReturn(run func() string) *MockConsumerGroupClaim_Topic_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConsumerGroupClaim creates a new instance of MockConsumerGroupClaim. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumerGroupClaim(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumerGroupClaim {
	mock := &MockConsumerGroupClaim{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
