// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	answerprocessor "github.com/itimky/spindle/pkg/domain/answer-processor"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockrelationStore is an autogenerated mock type for the relationStore type
type MockrelationStore struct {
	mock.Mock
}

type MockrelationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockrelationStore) EXPECT() *MockrelationStore_Expecter {
	return &MockrelationStore_Expecter{mock: &_m.Mock}
}

// GetOtherPersonAnswers provides a mock function with given fields: ctx, params
func (_m *MockrelationStore) GetOtherPersonAnswers(ctx context.Context, params answerprocessor.GetOtherPersonAnswersParams) (*answerprocessor.GetOtherPersonAnswersResult, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetOtherPersonAnswers")
	}

	var r0 *answerprocessor.GetOtherPersonAnswersResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, answerprocessor.GetOtherPersonAnswersParams) (*answerprocessor.GetOtherPersonAnswersResult, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, answerprocessor.GetOtherPersonAnswersParams) *answerprocessor.GetOtherPersonAnswersResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*answerprocessor.GetOtherPersonAnswersResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, answerprocessor.GetOtherPersonAnswersParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockrelationStore_GetOtherPersonAnswers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOtherPersonAnswers'
type MockrelationStore_GetOtherPersonAnswers_Call struct {
	*mock.Call
}

// GetOtherPersonAnswers is a helper method to define mock.On call
//   - ctx context.Context
//   - params answerprocessor.GetOtherPersonAnswersParams
func (_e *MockrelationStore_Expecter) GetOtherPersonAnswers(ctx interface{}, params interface{}) *MockrelationStore_GetOtherPersonAnswers_Call {
	return &MockrelationStore_GetOtherPersonAnswers_Call{Call: _e.mock.On("GetOtherPersonAnswers", ctx, params)}
}

func (_c *MockrelationStore_GetOtherPersonAnswers_Call) Run(run func(ctx context.Context, params answerprocessor.GetOtherPersonAnswersParams)) *MockrelationStore_GetOtherPersonAnswers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(answerprocessor.GetOtherPersonAnswersParams))
	})
	return _c
}

func (_c *MockrelationStore_GetOtherPersonAnswers_Call) Return(_a0 *answerprocessor.GetOtherPersonAnswersResult, _a1 error) *MockrelationStore_GetOtherPersonAnswers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockrelationStore_GetOtherPersonAnswers_Call) RunAndReturn(run func(context.Context, answerprocessor.GetOtherPersonAnswersParams) (*answerprocessor.GetOtherPersonAnswersResult, error)) *MockrelationStore_GetOtherPersonAnswers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePersonsWeights provides a mock function with given fields: ctx, params
func (_m *MockrelationStore) UpdatePersonsWeights(ctx context.Context, params answerprocessor.UpdatePersonsWeightsParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePersonsWeights")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, answerprocessor.UpdatePersonsWeightsParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockrelationStore_UpdatePersonsWeights_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePersonsWeights'
type MockrelationStore_UpdatePersonsWeights_Call struct {
	*mock.Call
}

// UpdatePersonsWeights is a helper method to define mock.On call
//   - ctx context.Context
//   - params answerprocessor.UpdatePersonsWeightsParams
func (_e *MockrelationStore_Expecter) UpdatePersonsWeights(ctx interface{}, params interface{}) *MockrelationStore_UpdatePersonsWeights_Call {
	return &MockrelationStore_UpdatePersonsWeights_Call{Call: _e.mock.On("UpdatePersonsWeights", ctx, params)}
}

func (_c *MockrelationStore_UpdatePersonsWeights_Call) Run(run func(ctx context.Context, params answerprocessor.UpdatePersonsWeightsParams)) *MockrelationStore_UpdatePersonsWeights_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(answerprocessor.UpdatePersonsWeightsParams))
	})
	return _c
}

func (_c *MockrelationStore_UpdatePersonsWeights_Call) Return(_a0 error) *MockrelationStore_UpdatePersonsWeights_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockrelationStore_UpdatePersonsWeights_Call) RunAndReturn(run func(context.Context, answerprocessor.UpdatePersonsWeightsParams) error) *MockrelationStore_UpdatePersonsWeights_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockrelationStore creates a new instance of MockrelationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrelationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockrelationStore {
	mock := &MockrelationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
