// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	answerprocessor "github.com/itimky/spindle/pkg/domain/answer-processor"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockmatrixStore is an autogenerated mock type for the matrixStore type
type MockmatrixStore struct {
	mock.Mock
}

type MockmatrixStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockmatrixStore) EXPECT() *MockmatrixStore_Expecter {
	return &MockmatrixStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, questionID
func (_m *MockmatrixStore) Get(ctx context.Context, questionID answerprocessor.GetWeightMatrixParams) (answerprocessor.WeightMatrix, error) {
	ret := _m.Called(ctx, questionID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 answerprocessor.WeightMatrix
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, answerprocessor.GetWeightMatrixParams) (answerprocessor.WeightMatrix, error)); ok {
		return rf(ctx, questionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, answerprocessor.GetWeightMatrixParams) answerprocessor.WeightMatrix); ok {
		r0 = rf(ctx, questionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(answerprocessor.WeightMatrix)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, answerprocessor.GetWeightMatrixParams) error); ok {
		r1 = rf(ctx, questionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockmatrixStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockmatrixStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - questionID answerprocessor.GetWeightMatrixParams
func (_e *MockmatrixStore_Expecter) Get(ctx interface{}, questionID interface{}) *MockmatrixStore_Get_Call {
	return &MockmatrixStore_Get_Call{Call: _e.mock.On("Get", ctx, questionID)}
}

func (_c *MockmatrixStore_Get_Call) Run(run func(ctx context.Context, questionID answerprocessor.GetWeightMatrixParams)) *MockmatrixStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(answerprocessor.GetWeightMatrixParams))
	})
	return _c
}

func (_c *MockmatrixStore_Get_Call) Return(_a0 answerprocessor.WeightMatrix, _a1 error) *MockmatrixStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockmatrixStore_Get_Call) RunAndReturn(run func(context.Context, answerprocessor.GetWeightMatrixParams) (answerprocessor.WeightMatrix, error)) *MockmatrixStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockmatrixStore creates a new instance of MockmatrixStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockmatrixStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockmatrixStore {
	mock := &MockmatrixStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
